# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.ops.conv2d import conv2d_output_size
from flag_gems.ops.conv3d import conv3d
from flag_gems.ops.conv_transpose1d import conv_transpose1d
from flag_gems.ops.conv_transpose2d import conv_transpose2d
from flag_gems.utils import libentry

logger = logging.getLogger(__name__)

# tl.dot requires the contraction dim K >= 16. The im2col matmul contracts over
# the (padded) per-group input channel count, so channels are padded up to this.
_MIN_DOT_K = 16


def _forward_configs():
    """Autotune space for the operator-local im2col forward kernel.

    Kept self-contained here (rather than reusing the shared ``conv2d_forward``
    tuning table) so ``convolution_overrideable`` can explore wider N*Ho*Wo and
    Co tiles plus deeper software pipelining without changing the shared conv
    kernels that conv1d/conv2d/conv3d rely on.
    """
    configs = []
    for block_nhw in (32, 64, 128, 256):
        for block_co in (32, 64, 128):
            for num_stages in (2, 3, 4):
                # Small tiles are launch/latency bound, so give them the low warp
                # counts that keep occupancy up; large tiles need more warps to
                # cover the wider matmul.
                warp_choices = (2, 4) if block_nhw <= 64 else (4, 8)
                for num_warps in warp_choices:
                    configs.append(
                        triton.Config(
                            {
                                "BLOCK_NI_HO_WO": block_nhw,
                                "BLOCK_CO": block_co,
                                "BLOCK_CI": 32,
                            },
                            num_stages=num_stages,
                            num_warps=num_warps,
                        )
                    )
    return configs


@libentry()
@triton.autotune(
    configs=_forward_configs(),
    key=[
        "in_n",
        "weight_c",
        "input_height",
        "input_width",
        "out_c",
        "out_height",
        "out_width",
        "weight_height",
        "weight_width",
        "stride_height",
        "stride_width",
        "padding_height",
        "padding_width",
        "groups",
        # Tune per element size: the autotune cache is otherwise dtype-agnostic,
        # so an aggressive fp16/bf16 tile would be reused for fp32 and blow up
        # its shared-memory/register budget. Keying on the byte width keeps the
        # 32-bit path on its own (safer) config.
        "DTYPE_KEY",
    ],
)
@triton.jit
def _conv2d_forward_kernel(
    input_pointer,
    weight_pointer,
    output_pointer,
    bias_pointer,
    in_n,
    input_height,
    input_width,
    out_c,
    out_height,
    out_width,
    input_n_stride,
    input_c_stride,
    input_height_stride,
    input_width_stride,
    weight_n_stride,
    weight_c_stride,
    weight_height_stride,
    weight_width_stride,
    output_n_stride,
    output_c_stride,
    output_height_stride,
    output_width_stride,
    weight_c: tl.constexpr,
    weight_height: tl.constexpr,
    weight_width: tl.constexpr,
    stride_height: tl.constexpr,
    stride_width: tl.constexpr,
    padding_height: tl.constexpr,
    padding_width: tl.constexpr,
    dilation_height: tl.constexpr,
    dilation_width: tl.constexpr,
    groups: tl.constexpr,
    DTYPE_KEY: tl.constexpr,
    BLOCK_NI_HO_WO: tl.constexpr,
    BLOCK_CI: tl.constexpr,
    BLOCK_CO: tl.constexpr,
):
    pid_ni_ho_wo = tl.program_id(0)
    pid_co = tl.program_id(1)
    pid_group = tl.program_id(2)

    ni_ho_wo_offset = pid_ni_ho_wo * BLOCK_NI_HO_WO + tl.arange(0, BLOCK_NI_HO_WO)
    ni_ho_offset = ni_ho_wo_offset // out_width
    in_n_point_value = ni_ho_offset // out_height
    output_height_point_value = ni_ho_offset % out_height
    output_width_point_value = ni_ho_wo_offset % out_width

    out_per_group_c = out_c // groups
    output_c_offset = pid_co * BLOCK_CO + tl.arange(0, BLOCK_CO)
    input_pointer += (
        input_n_stride * in_n_point_value + input_c_stride * pid_group * weight_c
    )[:, None]
    weight_pointer += (
        weight_n_stride * output_c_offset
        + weight_n_stride * pid_group * out_per_group_c
    )[None, :]

    accum = tl.zeros((BLOCK_NI_HO_WO, BLOCK_CO), dtype=tl.float32)
    BLOCK_CI_COUNT = (weight_c + BLOCK_CI - 1) // BLOCK_CI
    for hwc in range(weight_height * weight_width * BLOCK_CI_COUNT):
        c = (hwc % BLOCK_CI_COUNT) * BLOCK_CI
        hw = hwc // BLOCK_CI_COUNT
        h = hw // weight_width
        w = hw % weight_width

        input_c_offset = c + tl.arange(0, BLOCK_CI)
        input_height_offset = (
            h * dilation_height
            - padding_height
            + stride_height * output_height_point_value
        )
        input_width_offset = (
            w * dilation_width - padding_width + stride_width * output_width_point_value
        )

        curr_input_pointer = (
            input_pointer
            + (input_c_stride * input_c_offset)[None, :]
            + (input_height_stride * input_height_offset)[:, None]
            + (input_width_stride * input_width_offset)[:, None]
        )
        curr_weight_pointer = (
            weight_pointer
            + (weight_c_stride * input_c_offset)[:, None]
            + (weight_height_stride * h)
            + (weight_width_stride * w)
        )

        input_mask = (
            (in_n_point_value < in_n)[:, None]
            & (input_c_offset < weight_c)[None, :]
            & (0 <= input_height_offset)[:, None]
            & (input_height_offset < input_height)[:, None]
            & (0 <= input_width_offset)[:, None]
            & (input_width_offset < input_width)[:, None]
        )
        weight_mask = (input_c_offset < weight_c)[:, None] & (
            output_c_offset < out_per_group_c
        )[None, :]

        input_block = tl.load(curr_input_pointer, mask=input_mask)
        weight_block = tl.load(curr_weight_pointer, mask=weight_mask)

        accum += tl.dot(input_block, weight_block, allow_tf32=False)
    bias_pointer += (pid_group[None] * out_per_group_c)[None, :] + output_c_offset[
        None, :
    ]
    mask_bias = (output_c_offset < out_per_group_c)[None, :]
    bias = tl.load(bias_pointer, mask_bias).to(tl.float32)
    accum += bias
    output_pointer += (
        (output_n_stride * in_n_point_value)[:, None]
        + (output_c_stride * (pid_group * out_per_group_c + output_c_offset))[None, :]
        + (output_height_stride * output_height_point_value)[:, None]
        + (output_width_stride * output_width_point_value)[:, None]
    )
    output_mask = (
        (in_n_point_value < in_n)[:, None]
        & (output_c_offset < out_per_group_c)[None, :]
        & (output_height_point_value < out_height)[:, None]
        & (output_width_point_value < out_width)[:, None]
    )

    tl.store(output_pointer, accum, mask=output_mask)


def _pair(value):
    if isinstance(value, (list, tuple)):
        if len(value) == 1:
            return int(value[0]), int(value[0])
        return int(value[0]), int(value[1])
    return int(value), int(value)


def _conv2d_forward(input, weight, bias, stride, padding, dilation, groups):
    """2D forward convolution driven directly by the Triton im2col kernel."""
    stride_height, stride_width = _pair(stride)
    padding_height, padding_width = _pair(padding)
    dilation_height, dilation_width = _pair(dilation)

    in_n, _, input_height, input_width = input.shape
    out_c, weight_c, weight_height, weight_width = weight.shape

    # Pad channels to satisfy the tl.dot K >= 16 constraint.
    if weight_c < _MIN_DOT_K:
        pad_c = _MIN_DOT_K - weight_c
        if groups == 1:
            input = torch.nn.functional.pad(input, (0, 0, 0, 0, 0, pad_c))
        else:
            N, C, H, W = input.shape
            input = input.reshape(N, groups, weight_c, H, W)
            input = torch.nn.functional.pad(input, (0, 0, 0, 0, 0, pad_c))
            input = input.reshape(N, groups * (weight_c + pad_c), H, W)
        weight = torch.nn.functional.pad(weight, (0, 0, 0, 0, 0, pad_c))
        weight_c = weight_c + pad_c

    out_height = conv2d_output_size(
        input_height, weight_height, stride_height, padding_height, dilation_height
    )
    out_width = conv2d_output_size(
        input_width, weight_width, stride_width, padding_width, dilation_width
    )

    output_dtype = input.dtype
    output = torch.empty(
        (in_n, out_c, out_height, out_width),
        device=input.device,
        dtype=output_dtype,
    )

    grid = lambda META: (  # noqa: E731
        triton.cdiv(in_n * out_height * out_width, META["BLOCK_NI_HO_WO"]),
        triton.cdiv(int(out_c // groups), META["BLOCK_CO"]),
        groups,
    )

    if bias is None:
        bias_pointer = torch.zeros(out_c, device=input.device, dtype=output_dtype)
    else:
        bias_pointer = bias

    _conv2d_forward_kernel[grid](
        input,
        weight,
        output,
        bias_pointer,
        in_n,
        input_height,
        input_width,
        out_c,
        out_height,
        out_width,
        *input.stride(),
        *weight.stride(),
        *output.stride(),
        weight_c,
        weight_height,
        weight_width,
        stride_height,
        stride_width,
        padding_height,
        padding_width,
        dilation_height,
        dilation_width,
        groups=groups,
        DTYPE_KEY=input.element_size(),
    )
    return output


def _convolution_overrideable_impl(
    input,
    weight,
    bias,
    stride,
    padding,
    dilation,
    transposed,
    output_padding,
    groups,
):
    """Generic convolution dispatch backed by FlagGems Triton conv kernels.

    Mirrors ``aten::convolution_overrideable``: the spatial rank is inferred
    from ``weight.ndim - 2`` and the call is routed to the matching FlagGems
    Triton implementation.
    """
    spatial_dims = weight.ndim - 2
    assert spatial_dims in (1, 2, 3), (
        f"convolution_overrideable only supports 1D/2D/3D convolutions, "
        f"received weight with shape {tuple(weight.shape)}"
    )

    if transposed:
        if spatial_dims == 1:
            return conv_transpose1d(
                input, weight, bias, stride, padding, output_padding, groups, dilation
            )
        if spatial_dims == 2:
            return conv_transpose2d(
                input, weight, bias, stride, padding, output_padding, groups, dilation
            )
        raise NotImplementedError(
            "convolution_overrideable does not support 3D transposed convolution."
        )

    if spatial_dims == 1:
        # Reuse the 2D Triton kernel by promoting the single spatial axis.
        stride_w = _pair(stride)[0]
        padding_w = _pair(padding)[0]
        dilation_w = _pair(dilation)[0]
        return _conv2d_forward(
            input.unsqueeze(-1),
            weight.unsqueeze(-1),
            bias,
            (stride_w, 1),
            (padding_w, 0),
            (dilation_w, 1),
            groups,
        ).squeeze(-1)
    if spatial_dims == 2:
        return _conv2d_forward(input, weight, bias, stride, padding, dilation, groups)
    return conv3d(input, weight, bias, stride, padding, dilation, groups)


def convolution_overrideable(
    input,
    weight,
    bias,
    stride,
    padding,
    dilation,
    transposed,
    output_padding,
    groups,
):
    logger.debug("GEMS CONVOLUTION_OVERRIDEABLE")
    return _convolution_overrideable_impl(
        input,
        weight,
        bias,
        stride,
        padding,
        dilation,
        transposed,
        output_padding,
        groups,
    )


def convolution_overrideable_out(
    input,
    weight,
    bias,
    stride,
    padding,
    dilation,
    transposed,
    output_padding,
    groups,
    *,
    out,
):
    logger.debug("GEMS CONVOLUTION_OVERRIDEABLE_OUT")
    result = _convolution_overrideable_impl(
        input,
        weight,
        bias,
        stride,
        padding,
        dilation,
        transposed,
        output_padding,
        groups,
    )
    out.copy_(result)
    return out
